### ISSUE TITLE
Identyfikacja ULDK przestała działać

### ISSUE THREAD

**Issue by panmaro** [gis-support/gis-support-plugin#16]
Przy próbie rozwinięcia listy województw pojawia się błąd:
```
Traceback (most recent call last):
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\modules\teryt_search\main.py", line 193, in fill_combobox_province
              provinces = self.get_administratives("wojewodztwo")
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\modules\teryt_search\main.py", line 178, in get_administratives
              result = search.search(teryt)
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\uldk\api.py", line 124, in search
              raise e
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\uldk\api.py", line 116, in search
              result = self._decorated.search(*args, **kwargs)
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\uldk\api.py", line 134, in search
              return super().search()
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\uldk\api_limits.py", line 131, in wrapper
              return func(*args, **kargs)
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\uldk\api_limits.py", line 98, in wrapper
              return func(*args, **kargs)
              File "/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gissupport_plugin\modules\uldk\uldk\api.py", line 77, in search
              content = u.read()
              File "C:\programy\QGIS32~1.3\apps\Python39\lib\http\client.py", line 468, in read
              s = self._safe_read(self.length)
              File "C:\programy\QGIS32~1.3\apps\Python39\lib\http\client.py", line 609, in _safe_read
              data = self.fp.read(amt)
              File "C:\programy\QGIS32~1.3\apps\Python39\lib\socket.py", line 704, in readinto
              return self._sock.recv_into(b)
              File "C:\programy\QGIS32~1.3\apps\Python39\lib\ssl.py", line 1241, in recv_into
              return self.read(nbytes, buffer)
              File "C:\programy\QGIS32~1.3\apps\Python39\lib\ssl.py", line 1099, in read
              return self._sslobj.read(len, buffer)
             OverflowError: Python int too large to convert to C long
```

Warstwy z wynikami z ULDK też nie działają.

**Comment by gis-support** [comment]
Dzień dobry,

Dziękujemy za zgłoszenie problemu technicznego.
Nasza wtyczka udostępnia dane przekazywane przez GUGIK.
To właśnie w GUGIK pojawił się problem z dostępem do serwera.
Jesteśmy na etapie wyjaśniania problemu, proszę o wyrozumiałość.

Pozdrawiam serdecznie,

*Marta Gendaszyk*

*Specjalista ds. marketingu i sprzedaży tel: +48 570 979
682---------------------------------GIS Support Sp. z o.o.Konrada
Wallenroda 2f/3.09, Lublin 20-607
<https://goo.gl/maps/BpSvrK4abs6ur7Ro8>NIP: 9462641761Najlepsze szkolenia
QGIS w Polsce www.gis-support.pl/szkolenia-gis
<https://www.gis-support.pl/szkolenia-gis>*


śr., 23 lut 2022 o 13:34 'maro' via info ***@***.***> napisał(a):

**Comment by panmaro** [comment]
Faktycznie błąd musiał być po stronie GUGIK. Dzisiaj wszystko działa normalnie.
Dziękuję za błyskawiczną odpowiedź i pozdrawiam.
