### ISSUE TITLE
Błąd po update

### ISSUE THREAD

**Issue by AlexMaslanka** [gis-support/gis-support-plugin#18]
Nie można wczytać wtyczki 'uldk_gugik' z powodu błędu wywołania jej metody classFactory() 

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "", line 3, in raise_from
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by gis-support** [comment]
Dziękujemy za kontakt. Nastąpiło jednak nieporozumienie i nie jesteśmy autorami wtyczki do której chciałby Pan zgłosić błąd. 

Jednocześnie zachęcamy do pracy z Wtyczką GIS Support, której jesteśmy autorami i którą wspieramy. Więcej na https://gis-support.pl/wtyczka-gis-support/
