### ISSUE TITLE
KeyError podczas odznaczania wtyczki

### ISSUE THREAD

**Issue by Mativane** [gis-support/gis-support-plugin#6]
Podczas odznaczania aktywnej wtyczki w menedżerze wtyczek wyskakuje komunikat KeyError:

```
Error while unloading plugin gissupport_plugin 

KeyError: 'gissupport_plugin' 
Traceback (most recent call last):
  File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 393, in unloadPlugin
    _unloadPluginModules(packageName)
  File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 422, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'gissupport_plugin'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c068 
```

Pomimo błędu wtyczka faktycznie poprawnie się odznacza i staje nieaktywna, niemniej za każdym razem i tak wyskakuje ten sam komunikat o błędzie.

**Comment by gis-support** [comment]
Problem został rozwiązany w wersji 1.2.6
